//! V16 libSQL migration helpers for `agent_jobs` context fields.

use std::collections::BTreeSet;

use super::MigrationContext;

pub(super) const V16_NAME: &str = "agent_jobs_context_fields";
pub(super) const V16_SQL_MARKER: &str =
    "-- generated by apply_agent_jobs_context_fields_migration()";

pub(super) async fn collect_existing_columns(
    conn: &libsql::Connection,
    ctx: MigrationContext<'_>,
) -> Result<BTreeSet<String>, crate::error::DatabaseError> {
    let MigrationContext { version, name } = ctx;
    use crate::error::DatabaseError;

    let mut rows = conn
        .query("PRAGMA table_info(agent_jobs)", ())
        .await
        .map_err(|e| {
            DatabaseError::Migration(format!(
                "libSQL migration V{version} ({name}): failed to inspect agent_jobs schema: {e}"
            ))
        })?;
    let mut columns = BTreeSet::new();

    while let Some(row) = rows.next().await.map_err(|e| {
        DatabaseError::Migration(format!(
            "libSQL migration V{version} ({name}): failed to read agent_jobs schema: {e}"
        ))
    })? {
        let column_name = row.get::<String>(1).map_err(|e| {
            DatabaseError::Migration(format!(
                "libSQL migration V{version} ({name}): failed to decode agent_jobs column name: {e}"
            ))
        })?;
        columns.insert(column_name);
    }

    Ok(columns)
}

pub(super) fn missing_context_field_statements(columns: &BTreeSet<String>) -> Vec<&'static str> {
    let mut statements = Vec::new();
    if !columns.contains("transitions") {
        statements
            .push("ALTER TABLE agent_jobs ADD COLUMN transitions TEXT NOT NULL DEFAULT '[]';");
    }
    if !columns.contains("metadata") {
        statements.push("ALTER TABLE agent_jobs ADD COLUMN metadata TEXT NOT NULL DEFAULT '{}';");
    }
    if !columns.contains("user_timezone") {
        statements
            .push("ALTER TABLE agent_jobs ADD COLUMN user_timezone TEXT NOT NULL DEFAULT 'UTC';");
    }

    statements
}

pub(super) async fn apply_agent_jobs_context_fields_migration(
    conn: &libsql::Connection,
    ctx: MigrationContext<'_>,
) -> Result<(), crate::error::DatabaseError> {
    let MigrationContext { version, name } = ctx;
    use crate::error::DatabaseError;

    conn.execute_batch("BEGIN IMMEDIATE;").await.map_err(|e| {
        DatabaseError::Migration(format!(
            "libSQL migration V{version}: failed to start transaction: {e}"
        ))
    })?;

    let result: Result<(), DatabaseError> = async {
        let columns = collect_existing_columns(conn, MigrationContext { version, name }).await?;
        let statements = missing_context_field_statements(&columns);

        if !statements.is_empty() {
            conn.execute_batch(&statements.join("\n"))
                .await
                .map_err(|e| {
                    DatabaseError::Migration(format!(
                        "libSQL migration V{version} ({name}) failed: {e}"
                    ))
                })?;
        }

        conn.execute(
            "INSERT INTO _migrations (version, name) VALUES (?1, ?2)",
            libsql::params![version, name],
        )
        .await
        .map_err(|e| {
            DatabaseError::Migration(format!(
                "Failed to record migration V{version} ({name}): {e}"
            ))
        })?;

        Ok(())
    }
    .await;

    match result {
        Ok(()) => {
            conn.execute_batch("COMMIT;").await.map_err(|e| {
                DatabaseError::Migration(format!(
                    "libSQL migration V{version} ({name}): commit failed: {e}"
                ))
            })?;
            Ok(())
        }
        Err(error) => {
            if let Err(cleanup_error) = conn.execute_batch("ROLLBACK;").await {
                tracing::warn!(
                    version,
                    name,
                    error = %cleanup_error,
                    "libSQL V16 rollback failed"
                );
            }
            Err(error)
        }
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use rstest::rstest;
    use tempfile::tempdir;

    use super::{V16_NAME, collect_existing_columns, missing_context_field_statements};
    use crate::db::libsql_migrations::run_incremental;
    use crate::db::libsql_migrations::{INCREMENTAL_MIGRATIONS, MigrationContext};

    fn existing_columns(entries: &[&str]) -> BTreeSet<String> {
        entries.iter().map(|entry| (*entry).to_string()).collect()
    }

    #[rstest]
    #[case(&[] as &[&str], vec![
        "ALTER TABLE agent_jobs ADD COLUMN transitions TEXT NOT NULL DEFAULT '[]';",
        "ALTER TABLE agent_jobs ADD COLUMN metadata TEXT NOT NULL DEFAULT '{}';",
        "ALTER TABLE agent_jobs ADD COLUMN user_timezone TEXT NOT NULL DEFAULT 'UTC';",
    ])]
    #[case(&["transitions"], vec![
        "ALTER TABLE agent_jobs ADD COLUMN metadata TEXT NOT NULL DEFAULT '{}';",
        "ALTER TABLE agent_jobs ADD COLUMN user_timezone TEXT NOT NULL DEFAULT 'UTC';",
    ])]
    #[case(&["metadata"], vec![
        "ALTER TABLE agent_jobs ADD COLUMN transitions TEXT NOT NULL DEFAULT '[]';",
        "ALTER TABLE agent_jobs ADD COLUMN user_timezone TEXT NOT NULL DEFAULT 'UTC';",
    ])]
    #[case(&["user_timezone"], vec![
        "ALTER TABLE agent_jobs ADD COLUMN transitions TEXT NOT NULL DEFAULT '[]';",
        "ALTER TABLE agent_jobs ADD COLUMN metadata TEXT NOT NULL DEFAULT '{}';",
    ])]
    #[case(&["transitions", "metadata"], vec![
        "ALTER TABLE agent_jobs ADD COLUMN user_timezone TEXT NOT NULL DEFAULT 'UTC';",
    ])]
    #[case(&["transitions", "user_timezone"], vec![
        "ALTER TABLE agent_jobs ADD COLUMN metadata TEXT NOT NULL DEFAULT '{}';",
    ])]
    #[case(&["metadata", "user_timezone"], vec![
        "ALTER TABLE agent_jobs ADD COLUMN transitions TEXT NOT NULL DEFAULT '[]';",
    ])]
    #[case(&["transitions", "metadata", "user_timezone"], Vec::new())]
    fn missing_context_field_statements_handles_all_column_subsets(
        #[case] present_columns: &[&str],
        #[case] expected: Vec<&'static str>,
    ) {
        let columns = existing_columns(present_columns);
        assert_eq!(missing_context_field_statements(&columns), expected);
    }

    #[tokio::test]
    async fn run_incremental_applies_v16_once_to_partially_migrated_agent_jobs() {
        let dir = tempdir().expect("tempdir should be created");
        let db_path = dir.path().join("v16-context.db");
        let db = libsql::Builder::new_local(&db_path)
            .build()
            .await
            .expect("libsql db should build");
        let conn = db.connect().expect("connection should succeed");

        conn.execute_batch(
            r#"
            CREATE TABLE _migrations (
                version INTEGER PRIMARY KEY,
                name TEXT NOT NULL,
                applied_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
            );
            CREATE TABLE agent_jobs (
                id TEXT PRIMARY KEY,
                title TEXT NOT NULL DEFAULT '',
                description TEXT NOT NULL DEFAULT '{}',
                status TEXT NOT NULL DEFAULT 'pending',
                source TEXT NOT NULL DEFAULT 'direct'
            );
            "#,
        )
        .await
        .expect("base schema should be created");

        for &(version, name, _) in INCREMENTAL_MIGRATIONS
            .iter()
            .filter(|(version, _, _)| *version < 16)
        {
            conn.execute(
                "INSERT INTO _migrations (version, name) VALUES (?1, ?2)",
                libsql::params![version, name],
            )
            .await
            .expect("prior migration should seed");
        }

        run_incremental(&conn)
            .await
            .expect("V16 migration should apply");
        run_incremental(&conn)
            .await
            .expect("V16 migration rerun should be idempotent");

        let columns = collect_existing_columns(
            &conn,
            MigrationContext {
                version: 16,
                name: V16_NAME,
            },
        )
        .await
        .expect("schema probe should succeed");
        assert!(columns.contains("transitions"));
        assert!(columns.contains("metadata"));
        assert!(columns.contains("user_timezone"));

        let mut rows = conn
            .query(
                "SELECT COUNT(*) FROM _migrations WHERE version = ?1 AND name = ?2",
                libsql::params![16, V16_NAME],
            )
            .await
            .expect("migration row query should succeed");
        let row = rows
            .next()
            .await
            .expect("migration row should read")
            .expect("migration row should exist");
        let count = row.get::<i64>(0).expect("count should decode");
        assert_eq!(count, 1);
    }
}
