"""Contracts for how CI installs tools and owns caches.

Two failure modes cost real money and real minutes here. A tool that
compiles from source rebuilds a published binary on every run. A cache with
two owners, or one that archives a `target` tree, writes gigabytes that the
next run mostly discards; the Ubicloud listing on 2026-09-03 showed 4.1 to
4.4 GB `v0-rust-*-tests` archives from exactly that shape. These tests pin
the contracts that keep both out.

Run via ``make test-workflow-contracts``.
"""

from __future__ import annotations

import re

import pytest
from _workflow_policy import (
    CACHE_ACTION_SHA,
    SHA_RE,
    SOURCE_BUILD_PATTERNS,
    Job,
    cache_paths,
    is_cache_step,
    jobs,
    load,
    step_text,
    workflow_paths,
)

ALL_JOBS: tuple[Job, ...] = tuple(jobs())

#: Commands whose first use must be preceded by their installer step. The
#: value is the step-name fragment that installs the command.
INSTALLER_BEFORE_USE: dict[str, str] = {
    "cargo nextest": "Install cargo-nextest",
    "cargo component": "Install cargo-component",
    "cargo llvm-cov": "Install cargo-llvm-cov",
    "cargo audit": "Install cargo-audit",
}

#: `release.yml` is generated by dist and regenerated wholesale on a version
#: bump, so its build matrix keeps the cache wiring dist emits. It runs only
#: on a tag push, always on GitHub-hosted runners, and never on Ubicloud, so
#: it is outside the runner-cost contract.
DIST_GENERATED = "release.yml"


def _ids(candidates: tuple[Job, ...]) -> list[str]:
    """Return readable parameter identifiers for a job sequence."""
    return [str(job) for job in candidates]


@pytest.mark.parametrize("job", ALL_JOBS, ids=_ids(ALL_JOBS))
def test_no_job_builds_a_tool_from_source(job: Job) -> None:
    """Reject any step that compiles a CI tool instead of downloading it."""
    for step in job.steps:
        body = step_text(step)
        for pattern, reason in SOURCE_BUILD_PATTERNS:
            assert not pattern.search(body), (
                f"{job} step {step.get('name', '<unnamed>')!r} {reason}. Use a "
                "pinned, checksum-verified release archive instead."
            )


def test_setup_commands_passed_to_reusable_workflows_avoid_source_builds() -> None:
    """Apply the same rule to shell handed to a reusable workflow."""
    for path in workflow_paths():
        declared = load(path).get("jobs")
        if not isinstance(declared, dict):
            continue
        for job_id, body in declared.items():
            inputs = body.get("with") if isinstance(body, dict) else None
            if not isinstance(inputs, dict):
                continue
            commands = inputs.get("setup-commands")
            if not isinstance(commands, str):
                continue
            for pattern, reason in SOURCE_BUILD_PATTERNS:
                assert not pattern.search(commands), (
                    f"{path.name}:{job_id} setup-commands {reason}"
                )


@pytest.mark.parametrize("job", ALL_JOBS, ids=_ids(ALL_JOBS))
def test_tool_installers_pin_a_version_and_fail_closed(job: Job) -> None:
    """Pin every installed tool and forbid a silent source-build fallback."""
    for step in job.steps:
        uses = step.get("uses")
        if not isinstance(uses, str) or not uses.startswith("taiki-e/install-action@"):
            continue
        ref = uses.split("@", 1)[1]
        assert SHA_RE.match(ref), (
            f"{job} pins the installer to {ref!r}; use a full commit SHA so "
            "the installer itself cannot change under the repository"
        )
        inputs = step.get("with")
        assert isinstance(inputs, dict), f"{job} installer step must declare inputs"
        tool = inputs.get("tool")
        assert isinstance(tool, str) and "@" in tool, (
            f"{job} installs {tool!r} without a version pin"
        )
        assert inputs.get("fallback") == "none", (
            f"{job} installs {tool!r} without `fallback: none`; the default "
            "fallback can compile the tool from source"
        )


@pytest.mark.parametrize("job", ALL_JOBS, ids=_ids(ALL_JOBS))
def test_binstall_invocations_pin_every_package(job: Job) -> None:
    """Pin the version of anything installed through cargo-binstall.

    `taiki-e/install-action` carries no manifest for `cargo-component`, so
    that tool comes from cargo-binstall instead. The fail-closed strategies
    keep it from compiling, and the version pin keeps the installed binary
    reproducible.
    """
    for step in job.steps:
        body = step_text(step)
        if "cargo binstall" not in body:
            continue
        packages = re.findall(r"\bcargo-[a-z0-9-]+(?:@[^\s\"']+)?", body)
        installed = [name for name in packages if name != "cargo-binstall"]
        assert installed, f"{job} runs cargo binstall without naming a package"
        for name in installed:
            assert "@" in name, f"{job} installs {name!r} without a version pin"


@pytest.mark.parametrize("job", ALL_JOBS, ids=_ids(ALL_JOBS))
def test_installers_precede_first_use(job: Job) -> None:
    """Order each installer before the first step that runs its command."""
    names = [str(step.get("name", "")) for step in job.steps]
    for command, installer in INSTALLER_BEFORE_USE.items():
        install_at = next(
            (index for index, name in enumerate(names) if name == installer), None
        )
        use_at = next(
            (
                index
                for index, step in enumerate(job.steps)
                if re.search(rf"\b{re.escape(command)}\b", step_text(step))
            ),
            None,
        )
        if use_at is None:
            continue
        assert install_at is not None, f"{job} runs {command!r} but never installs it"
        assert install_at < use_at, (
            f"{job} runs {command!r} at step {use_at} before {installer!r} at "
            f"step {install_at}"
        )


@pytest.mark.parametrize("job", ALL_JOBS, ids=_ids(ALL_JOBS))
def test_cache_action_is_pinned_to_the_reviewed_commit(job: Job) -> None:
    """Pin the cache action: Ubicloud's proxy intercepts this version."""
    if job.workflow == DIST_GENERATED:
        pytest.skip("dist owns release.yml's generated cache wiring")
    for step in job.steps:
        if not is_cache_step(step):
            continue
        uses = str(step.get("uses"))
        assert uses.endswith(f"@{CACHE_ACTION_SHA}"), (
            f"{job} uses {uses!r}; every cache step must pin "
            f"actions/cache at {CACHE_ACTION_SHA} (v6.1.0)"
        )


@pytest.mark.parametrize("job", ALL_JOBS, ids=_ids(ALL_JOBS))
def test_no_cache_step_archives_a_target_tree(job: Job) -> None:
    """Keep compiler output out of cache archives; sccache owns it."""
    for step in job.steps:
        if not is_cache_step(step):
            continue
        for path in cache_paths(step):
            assert not path.split("/")[0] == "target", (
                f"{job} archives {path!r}. A target tree duplicates sccache's "
                "ownership of compiler output and inflates the cache quota."
            )


@pytest.mark.parametrize("job", ALL_JOBS, ids=_ids(ALL_JOBS))
def test_each_cache_path_has_one_owner_within_a_job(job: Job) -> None:
    """Forbid two cache keys in one job from claiming the same path.

    A restore step and its matching save step share one key, so they are one
    owner. Two different keys over the same path are two owners, and the
    second write silently discards or duplicates the first.
    """
    owners: dict[str, set[str]] = {}
    for step in job.steps:
        if not is_cache_step(step):
            continue
        inputs = step.get("with")
        key = str(inputs.get("key", "")) if isinstance(inputs, dict) else ""
        for path in cache_paths(step):
            owners.setdefault(path, set()).add(key)
    for path, keys in sorted(owners.items()):
        assert len(keys) == 1, (
            f"{job} caches {path!r} under {len(keys)} different keys; each "
            "mutable path needs exactly one owner"
        )


def test_the_cargo_registry_cache_has_exactly_one_writer_per_platform() -> None:
    """Keep one save step per key family so no two jobs race to publish."""
    writers: list[str] = []
    for job in ALL_JOBS:
        for step in job.steps:
            uses = step.get("uses")
            if isinstance(uses, str) and uses.startswith("actions/cache/save@"):
                condition = str(step.get("if", ""))
                assert "refs/heads/main" in condition, (
                    f"{job} saves a cache without restricting the write to "
                    "main; pull requests must restore and never save"
                )
                writers.append(str(job))
    # One Linux writer and one Windows writer, both in test.yml.
    assert sorted(writers) == ["test.yml:tests", "test.yml:windows-build"], (
        f"unexpected set of cache writers: {sorted(writers)}"
    )


def test_shared_action_references_are_pinned_to_a_commit() -> None:
    """Pin every leynos/shared-actions reference to a full commit SHA."""
    references = 0
    for path in workflow_paths():
        for match in re.finditer(
            r"leynos/shared-actions/[^@\s]+@(\S+)", path.read_text(encoding="utf-8")
        ):
            references += 1
            ref = match.group(1)
            assert SHA_RE.match(ref), (
                f"{path.name} references shared-actions at {ref!r}; use a full "
                "commit SHA, never a branch or tag"
            )
    assert references > 0, "the estate should still consume shared actions"
